import json
import re
import unittest
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
APP=(ROOT/"app.js").read_text(encoding="utf-8")
SCRIPT=(ROOT/".github/scripts/build_news_snapshot.py").read_text(encoding="utf-8")
WORKFLOW=(ROOT/".github/workflows/news-snapshot.yml").read_text(encoding="utf-8")


class NewsHotSnapshotContractTest(unittest.TestCase):
    def test_snapshot_is_background_and_database_free(self):
        self.assertIn("google-news-rss-only-snapshot",SCRIPT)
        self.assertIn('"database":False',SCRIPT)
        self.assertNotIn("supabase.table",SCRIPT.lower())
        self.assertNotIn("supabase.table",SCRIPT.lower())
        self.assertNotIn(".table(",SCRIPT)
        self.assertNotIn(".update(",SCRIPT)

    def test_snapshot_refreshes_at_fastest_github_schedule(self):
        self.assertIn('cron: "*/5 * * * *"',WORKFLOW)
        self.assertIn("workflow_dispatch:",WORKFLOW)
        self.assertIn("news-cache",WORKFLOW)
        self.assertIn("googlenewsdecoder==0.1.7",WORKFLOW)
        self.assertIn("ftfy==6.3.1",WORKFLOW)
        self.assertIn("Build Google News candidate snapshot",WORKFLOW)
        self.assertIn("Resolve URLs, clean titles and require thumbnails",WORKFLOW)
        self.assertIn("Publish complete READY set atomically",WORKFLOW)
        self.assertIn("matrix:",WORKFLOW)
        self.assertIn("topic: thoi-su",WORKFLOW)
        self.assertIn("topic: kinh-doanh",WORKFLOW)
        self.assertIn("topic: tap-hoa",WORKFLOW)
        self.assertIn("topic: cong-nghe",WORKFLOW)
        self.assertIn("topic: the-thao",WORKFLOW)
        self.assertIn("topic: giai-tri",WORKFLOW)
        self.assertIn("topic: suc-khoe",WORKFLOW)
        self.assertIn("candidates: 180",WORKFLOW)
        self.assertIn('\\\"ready\\\":true',WORKFLOW)
        self.assertEqual(WORKFLOW.count("git push --force origin HEAD:news-cache"),1)

    def test_hot_ranking_prefers_fresh_multi_source_rich_items(self):
        self.assertIn("def hot_score(item,now):",SCRIPT)
        self.assertIn("480-age",SCRIPT)
        self.assertIn('item.get("duplicate_count")',SCRIPT)
        self.assertIn('len(item.get("images") or [])',SCRIPT)
        self.assertIn("DISCOVERY_CANDIDATE_LIMIT=180",SCRIPT)
        self.assertIn("RICH_IMAGE_LIMIT=180",SCRIPT)
        self.assertIn("RICH_WORKERS=16",SCRIPT)
        self.assertIn("decode_google_url",SCRIPT)
        self.assertIn("gnewsdecoder(value,interval=0)",SCRIPT)
        self.assertIn("enrich_article",SCRIPT)
        self.assertIn("candidates=list(items[:RICH_IMAGE_LIMIT])",SCRIPT)
        self.assertIn("def title_is_clean(v):",SCRIPT)
        self.assertIn("def ready_item(item):",SCRIPT)
        self.assertIn('data["ready"]=True',SCRIPT)
        self.assertIn('data["image_count"]=len(data["items"])',SCRIPT)
        self.assertIn("page_images",SCRIPT)
        self.assertIn("chia-se-mxh",SCRIPT)
        self.assertIn('"/templates/"',SCRIPT)
        self.assertIn("*page_images(text,final)",SCRIPT)
        self.assertIn("*(item.get(\"images\") or [])",SCRIPT)
        self.assertIn("article_soup",SCRIPT)
        self.assertIn("NEWS_DOMAIN_RULES={",SCRIPT)
        self.assertIn('"vnexpress.net"',SCRIPT)
        self.assertIn('"vietnamnet.vn"',SCRIPT)
        self.assertIn('"dantri.com.vn"',SCRIPT)
        self.assertIn('"tuoitre.vn"',SCRIPT)
        self.assertIn('"thanhnien.vn"',SCRIPT)
        self.assertIn('"nguonluc.com.vn"',SCRIPT)
        self.assertIn('"vovgiaothong.vn"',SCRIPT)
        self.assertIn("strip_article_noise",SCRIPT)
        self.assertIn("image_from_tag",SCRIPT)
        self.assertIn("UnicodeDammit",SCRIPT)
        self.assertIn('"content":"",',SCRIPT)
        self.assertIn("beautifulsoup4==4.12.3",WORKFLOW)
        self.assertIn('data["phase"]="rich"',SCRIPT)
        self.assertIn('"phase":"candidate"',SCRIPT)
        self.assertNotIn("def fetch_source(",SCRIPT)
        self.assertIn("google_query_feed",SCRIPT)
        self.assertIn("google_top_feed",SCRIPT)
        self.assertIn("fetch_google_query",SCRIPT)
        self.assertIn('GOOGLE_HOT_QUERIES=[',SCRIPT)
        self.assertIn('"tap-hoa":["thuế","an toàn vệ sinh thực phẩm","hàng giả","hàng nhái","hộ kinh doanh"]',SCRIPT)
        for phrase in ["Tin nóng","Tin hot","Tăng giá","Chiến tranh","công an","xét xử","vĩ mô","tạm giam","khởi tố","thuế","chứng khoán","lừa đảo"]:
            self.assertIn(f'"{phrase}"',SCRIPT)
        self.assertIn("feedparser.parse",SCRIPT)
        self.assertIn("process_items",SCRIPT)
        self.assertIn("ftfy_fix_text",SCRIPT)

    def test_frontend_has_static_snapshot_fast_path(self):
        self.assertIn("NEWS_SNAPSHOT_BASE_URL",APP)
        self.assertIn("fetchNewsSnapshot",APP)
        self.assertNotIn("backgroundRefreshLatestNews",APP)
        self.assertIn('String(data.phase||"")!=="rich"',APP)
        self.assertIn("fetchNewsSnapshot(key,force)",APP)
        self.assertIn('data.ready!==true',APP)
        self.assertIn("NEWS_SNAPSHOT_BUCKET_MS=5*60*1000",APP)
        self.assertIn('cache:force?"no-store":"force-cache"',APP)
        self.assertIn("prewarmLatestNews",APP)
        self.assertIn("https://wsrv.nl/",APP)
        self.assertIn("bindNewsCardImages",APP)


if __name__=="__main__":
    unittest.main()
