from pathlib import Path

p=Path('taphoa-mobile-standard.js')
s=p.read_text('utf-8')
anchor='''  function queueAfterAsyncOwner(){\n    queueSync();queueSync(80);queueSync(320);queueSync(1000);\n  }\n\n'''
block='''  const IFRAME_TAP_SELECTOR="#mobileUserWork button,#mobileUserWork [role=\\"button\\"],#mobileStandardCartSheet button,#orderCustomerPicker button";\n  let iframePointerTap=null;\n  let iframeSyntheticGuard=null;\n  function iframeTapFallbackEnabled(){return isMobile()&&window.parent!==window}\n  document.addEventListener("pointerdown",event=>{\n    if(!iframeTapFallbackEnabled()||(event.pointerType!=="touch"&&event.pointerType!=="pen"))return;\n    const target=event.target.closest?.(IFRAME_TAP_SELECTOR);\n    if(!target||target.disabled)return;\n    iframePointerTap={pointerId:event.pointerId,target,x:event.clientX,y:event.clientY,at:Date.now()};\n  },true);\n  document.addEventListener("pointerup",event=>{\n    const tap=iframePointerTap;\n    iframePointerTap=null;\n    if(!tap||tap.pointerId!==event.pointerId||!tap.target.isConnected)return;\n    const moved=Math.hypot(event.clientX-tap.x,event.clientY-tap.y);\n    if(moved>10||Date.now()-tap.at>800)return;\n    event.preventDefault();\n    event.stopPropagation();\n    iframeSyntheticGuard={target:tap.target,until:performance.now()+700};\n    tap.target.click();\n  },true);\n  document.addEventListener("pointercancel",()=>{iframePointerTap=null;},true);\n  document.addEventListener("click",event=>{\n    const guard=iframeSyntheticGuard;\n    if(!guard||performance.now()>guard.until){iframeSyntheticGuard=null;return;}\n    const target=event.target.closest?.(IFRAME_TAP_SELECTOR);\n    if(event.isTrusted&&target===guard.target){\n      event.preventDefault();\n      event.stopImmediatePropagation();\n      iframeSyntheticGuard=null;\n    }\n  },true);\n\n'''
if 'IFRAME_TAP_SELECTOR' in s:
    raise SystemExit('tap fallback already present')
if anchor not in s:
    raise SystemExit('tap fallback anchor not found')
p.write_text(s.replace(anchor,anchor+block,1),'utf-8')

t=Path('tests/test_mobile_iframe_tap_fallback.py')
t.write_text('''from pathlib import Path\nimport unittest\nROOT=Path(__file__).resolve().parents[1]\nJS=ROOT.joinpath("taphoa-mobile-standard.js").read_text("utf-8")\nclass MobileIframeTapFallback(unittest.TestCase):\n    def test_touch_pointer_is_promoted_to_programmatic_click(self):\n        self.assertIn("IFRAME_TAP_SELECTOR", JS)\n        self.assertIn("event.pointerType!==\\\"touch\\\"", JS)\n        self.assertIn("tap.target.click()", JS)\n        self.assertIn("window.parent!==window", JS)\n    def test_scroll_gesture_is_not_promoted_to_click(self):\n        self.assertIn("Math.hypot(event.clientX-tap.x,event.clientY-tap.y)", JS)\n        self.assertIn("moved>10", JS)\n        self.assertIn("pointercancel", JS)\n    def test_native_followup_click_is_deduplicated(self):\n        self.assertIn("event.isTrusted&&target===guard.target", JS)\n        self.assertIn("stopImmediatePropagation()", JS)\nif __name__=="__main__": unittest.main()\n''','utf-8')
