-- Supplier price model v2
-- Supplier sheet owns only:
--   A = product_name
--   B = input_price_vnd (supplier cost)
-- Everything else below is owned by GETLINK and must survive supplier-sheet refreshes.
--
-- Current legacy column C (margin_thousand) is migrated once into
-- expected_profit_vnd. Future supplier sheets may contain only A:B.
--
-- Selling price = supplier cost + expected profit.
-- Actual profit = selling price - supplier cost.
-- Price-change history always follows supplier cost (column B), never selling price.

alter table public.getlink_supplier_products
  add column if not exists expected_profit_vnd bigint not null default 0,
  add column if not exists actual_profit_vnd bigint,
  add column if not exists previous_input_price_vnd bigint,
  add column if not exists supplier_price_delta_vnd bigint,
  add column if not exists supplier_price_direction text,
  add column if not exists supplier_price_changed_at timestamptz,
  add column if not exists supplier_price_last_seen_at timestamptz;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname='getlink_supplier_products_price_direction_check'
      and conrelid='public.getlink_supplier_products'::regclass
  ) then
    alter table public.getlink_supplier_products
      add constraint getlink_supplier_products_price_direction_check
      check (supplier_price_direction is null or supplier_price_direction in ('up','down'));
  end if;
end $$;

update public.getlink_supplier_products
set expected_profit_vnd =
  case
    when margin_thousand is not null then round(margin_thousand * 1000)::bigint
    when display_price_vnd is not null and input_price_vnd is not null
      then display_price_vnd - input_price_vnd
    else coalesce(expected_profit_vnd,0)
  end;

create table if not exists public.getlink_supplier_price_history (
  id bigint generated by default as identity primary key,
  source_key text not null,
  source_row integer not null,
  canonical_url text not null,
  product_name text not null,
  old_price_vnd bigint,
  new_price_vnd bigint not null,
  delta_vnd bigint,
  direction text not null
    check (direction in ('initial','up','down')),
  detected_at timestamptz not null default now(),
  source_reported_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists getlink_supplier_price_history_product_time_idx
  on public.getlink_supplier_price_history (canonical_url, detected_at desc);
create index if not exists getlink_supplier_price_history_source_row_idx
  on public.getlink_supplier_price_history (source_key, source_row, detected_at desc);

alter table public.getlink_supplier_price_history enable row level security;
revoke all on public.getlink_supplier_price_history from anon, authenticated;

create or replace function public.getlink_normalize_supplier_price_levels()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  supplier_cost bigint;
  expected_profit bigint;
  sell_price bigint;
  pack_qty numeric;
  unit_name text;
begin
  supplier_cost := new.input_price_vnd;

  -- Transitional compatibility:
  -- while the legacy sheet still has column C, a changed non-null C updates
  -- our expected profit. Once C disappears/nulls out, our saved value remains.
  if tg_op='INSERT' then
    if new.margin_thousand is not null then
      new.expected_profit_vnd := round(new.margin_thousand * 1000)::bigint;
    else
      new.expected_profit_vnd := coalesce(new.expected_profit_vnd,0);
    end if;
  elsif new.margin_thousand is distinct from old.margin_thousand
    and new.margin_thousand is not null then
    new.expected_profit_vnd := round(new.margin_thousand * 1000)::bigint;
  else
    new.expected_profit_vnd := coalesce(new.expected_profit_vnd,old.expected_profit_vnd,0);
  end if;

  expected_profit := coalesce(new.expected_profit_vnd,0);
  pack_qty := case
    when new.units_per_carton is not null and new.units_per_carton >= 1
      then new.units_per_carton
    else null
  end;
  unit_name := nullif(btrim(coalesce(new.retail_unit,'')),'');

  sell_price := case
    when supplier_cost is not null and supplier_cost > 0
      then supplier_cost + expected_profit
    else null
  end;
  new.display_price_vnd := sell_price;
  new.actual_profit_vnd := case
    when sell_price is not null and supplier_cost is not null
      then sell_price - supplier_cost
    else null
  end;

  if tg_op='INSERT' then
    new.previous_input_price_vnd := null;
    new.supplier_price_delta_vnd := null;
    new.supplier_price_direction := null;
    new.supplier_price_changed_at := coalesce(new.imported_at, now());
    new.supplier_price_last_seen_at := coalesce(new.updated_at, now());
  else
    new.supplier_price_last_seen_at := coalesce(new.updated_at, now());
    if new.input_price_vnd is distinct from old.input_price_vnd then
      new.previous_input_price_vnd := old.input_price_vnd;
      if new.input_price_vnd is not null and old.input_price_vnd is not null then
        new.supplier_price_delta_vnd := new.input_price_vnd - old.input_price_vnd;
        new.supplier_price_direction := case
          when new.input_price_vnd > old.input_price_vnd then 'up'
          when new.input_price_vnd < old.input_price_vnd then 'down'
          else null
        end;
      else
        new.supplier_price_delta_vnd := null;
        new.supplier_price_direction := null;
      end if;
      new.supplier_price_changed_at := now();
    end if;
  end if;

  if new.source_key='thuoc-la' then
    unit_name := coalesce(unit_name,'cây');
    new.retail_unit := unit_name;
    new.retail_packaging := '1 ' || unit_name;
    new.retail_price_vnd := sell_price;

    if pack_qty is not null and pack_qty > 1 and sell_price is not null then
      new.carton_price_vnd := round(sell_price * pack_qty)::bigint;
      new.primary_packaging := 'Thùng';
    else
      new.carton_price_vnd := null;
      new.primary_packaging := '1 ' || unit_name;
    end if;
  else
    new.retail_unit := coalesce(unit_name,'');
    new.primary_packaging := 'Thùng';
    new.carton_price_vnd := sell_price;

    if pack_qty is not null and pack_qty > 1 and sell_price is not null then
      new.retail_price_vnd := round(sell_price / pack_qty)::bigint;
      new.retail_packaging := '1 ' || coalesce(unit_name,'lẻ');
    else
      new.retail_price_vnd := null;
      new.retail_packaging := case
        when unit_name is not null then '1 ' || unit_name
        else ''
      end;
    end if;
  end if;

  return new;
end;
$$;

create or replace function public.getlink_log_supplier_price_change()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if tg_op='INSERT' then
    if new.input_price_vnd is not null and new.input_price_vnd > 0 then
      insert into public.getlink_supplier_price_history(
        source_key,source_row,canonical_url,product_name,
        old_price_vnd,new_price_vnd,delta_vnd,direction,detected_at
      ) values (
        new.source_key,new.source_row,new.canonical_url,new.product_name,
        null,new.input_price_vnd,null,'initial',
        coalesce(new.imported_at,now())
      );
    end if;
  elsif new.input_price_vnd is distinct from old.input_price_vnd
    and new.input_price_vnd is not null and new.input_price_vnd > 0
    and old.input_price_vnd is not null and old.input_price_vnd > 0 then
    insert into public.getlink_supplier_price_history(
      source_key,source_row,canonical_url,product_name,
      old_price_vnd,new_price_vnd,delta_vnd,direction,detected_at
    ) values (
      new.source_key,new.source_row,new.canonical_url,new.product_name,
      old.input_price_vnd,new.input_price_vnd,
      new.input_price_vnd-old.input_price_vnd,
      case when new.input_price_vnd>old.input_price_vnd then 'up' else 'down' end,
      now()
    );
  end if;
  return null;
end;
$$;

drop trigger if exists getlink_supplier_price_levels_before_write
  on public.getlink_supplier_products;
create trigger getlink_supplier_price_levels_before_write
before insert or update of
  source_key,input_price_vnd,margin_thousand,expected_profit_vnd,
  units_per_carton,retail_unit,updated_at
on public.getlink_supplier_products
for each row
execute function public.getlink_normalize_supplier_price_levels();

drop trigger if exists getlink_supplier_price_history_after_write
  on public.getlink_supplier_products;
create trigger getlink_supplier_price_history_after_write
after insert or update of input_price_vnd
on public.getlink_supplier_products
for each row
execute function public.getlink_log_supplier_price_change();

update public.getlink_supplier_products
set expected_profit_vnd = expected_profit_vnd;

insert into public.getlink_supplier_price_history(
  source_key,source_row,canonical_url,product_name,
  old_price_vnd,new_price_vnd,delta_vnd,direction,detected_at
)
select p.source_key,p.source_row,p.canonical_url,p.product_name,
       null,p.input_price_vnd,null,'initial',
       coalesce(p.imported_at,p.updated_at,now())
from public.getlink_supplier_products p
where p.input_price_vnd is not null
  and p.input_price_vnd > 0
  and not exists (
    select 1
    from public.getlink_supplier_price_history h
    where h.canonical_url=p.canonical_url
  );
