begin;

create table if not exists public.getlink_sales_orders (
  id uuid primary key default gen_random_uuid(),
  order_no bigint generated by default as identity unique,
  customer_account_id uuid not null references public.v21_accounts(id),
  created_by_account_id uuid not null references public.v21_accounts(id),
  status text not null default 'pending' check (status in ('pending','delivered','reversed','cancelled')),
  note text not null default '',
  total_vnd bigint not null default 0 check (total_vnd >= 0),
  delivered_at timestamptz,
  reversed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.getlink_sales_order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.getlink_sales_orders(id) on delete cascade,
  product_url text not null,
  product_code text not null default '',
  product_name_snapshot text not null,
  qty integer not null check (qty > 0 and qty <= 999),
  unit_price_vnd bigint not null check (unit_price_vnd >= 0),
  line_no integer not null check (line_no > 0),
  note text not null default '',
  created_at timestamptz not null default now(),
  unique (order_id,line_no)
);

create table if not exists public.getlink_debt_ledger (
  id uuid primary key default gen_random_uuid(),
  customer_account_id uuid not null references public.v21_accounts(id),
  order_id uuid references public.getlink_sales_orders(id) on delete restrict,
  kind text not null check (kind in ('sale','reversal','collection','payment')),
  amount_vnd bigint not null,
  note text not null default '',
  created_by_account_id uuid not null references public.v21_accounts(id),
  created_at timestamptz not null default now()
);

create index if not exists getlink_sales_orders_customer_status_created_idx
  on public.getlink_sales_orders(customer_account_id,status,created_at desc);
create index if not exists getlink_sales_orders_status_created_idx
  on public.getlink_sales_orders(status,created_at desc);
create index if not exists getlink_sales_order_items_order_idx
  on public.getlink_sales_order_items(order_id,line_no);
create index if not exists getlink_debt_ledger_customer_created_idx
  on public.getlink_debt_ledger(customer_account_id,created_at desc);
create unique index if not exists getlink_debt_ledger_order_kind_once_idx
  on public.getlink_debt_ledger(order_id,kind)
  where order_id is not null and kind in ('sale','reversal');

alter table public.getlink_sales_orders enable row level security;
alter table public.getlink_sales_order_items enable row level security;
alter table public.getlink_debt_ledger enable row level security;

create or replace function public.getlink_sales_create_order(
  p_customer_account_id uuid,
  p_created_by_account_id uuid,
  p_note text,
  p_items jsonb
) returns public.getlink_sales_orders
language plpgsql
security definer
set search_path=public
as $$
declare
  v_order public.getlink_sales_orders;
  v_total bigint;
begin
  if p_customer_account_id is null or p_created_by_account_id is null then
    raise exception 'sales_account_required';
  end if;
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) < 1 or jsonb_array_length(p_items) > 100 then
    raise exception 'sales_items_invalid';
  end if;

  select coalesce(sum(
    greatest(0,(x.item->>'unit_price_vnd')::bigint) *
    greatest(1,(x.item->>'qty')::integer)
  ),0)::bigint
  into v_total
  from jsonb_array_elements(p_items) with ordinality as x(item,ord);

  insert into public.getlink_sales_orders(
    customer_account_id,created_by_account_id,status,note,total_vnd
  ) values (
    p_customer_account_id,p_created_by_account_id,'pending',coalesce(p_note,''),v_total
  ) returning * into v_order;

  insert into public.getlink_sales_order_items(
    order_id,product_url,product_code,product_name_snapshot,qty,unit_price_vnd,line_no,note
  )
  select
    v_order.id,
    coalesce(x.item->>'product_url',''),
    coalesce(x.item->>'product_code',''),
    coalesce(x.item->>'product_name_snapshot','Sản phẩm'),
    greatest(1,(x.item->>'qty')::integer),
    greatest(0,(x.item->>'unit_price_vnd')::bigint),
    x.ord::integer,
    coalesce(x.item->>'note','')
  from jsonb_array_elements(p_items) with ordinality as x(item,ord);

  return v_order;
end;
$$;

create or replace function public.getlink_sales_deliver_order(
  p_order_id uuid,
  p_actor_account_id uuid
) returns public.getlink_sales_orders
language plpgsql
security definer
set search_path=public
as $$
declare
  v_order public.getlink_sales_orders;
begin
  select * into v_order
  from public.getlink_sales_orders
  where id=p_order_id
  for update;

  if not found then raise exception 'sales_order_not_found'; end if;
  if v_order.status='delivered' then return v_order; end if;
  if v_order.status<>'pending' then raise exception 'sales_order_not_pending'; end if;

  update public.getlink_sales_orders
  set status='delivered',delivered_at=now(),updated_at=now()
  where id=p_order_id
  returning * into v_order;

  insert into public.getlink_debt_ledger(
    customer_account_id,order_id,kind,amount_vnd,note,created_by_account_id
  ) values (
    v_order.customer_account_id,v_order.id,'sale',v_order.total_vnd,'Đã giao',p_actor_account_id
  ) on conflict (order_id,kind) where order_id is not null and kind in ('sale','reversal') do nothing;

  return v_order;
end;
$$;

create or replace function public.getlink_sales_reverse_order(
  p_order_id uuid,
  p_actor_account_id uuid
) returns public.getlink_sales_orders
language plpgsql
security definer
set search_path=public
as $$
declare
  v_order public.getlink_sales_orders;
begin
  select * into v_order
  from public.getlink_sales_orders
  where id=p_order_id
  for update;

  if not found then raise exception 'sales_order_not_found'; end if;
  if v_order.status='reversed' then return v_order; end if;
  if v_order.status<>'delivered' then raise exception 'sales_order_not_delivered'; end if;

  update public.getlink_sales_orders
  set status='reversed',reversed_at=now(),updated_at=now()
  where id=p_order_id
  returning * into v_order;

  insert into public.getlink_debt_ledger(
    customer_account_id,order_id,kind,amount_vnd,note,created_by_account_id
  ) values (
    v_order.customer_account_id,v_order.id,'reversal',-v_order.total_vnd,'Hoàn đơn',p_actor_account_id
  ) on conflict (order_id,kind) where order_id is not null and kind in ('sale','reversal') do nothing;

  return v_order;
end;
$$;

create or replace function public.getlink_sales_delete_pending_order(
  p_order_id uuid
) returns uuid
language plpgsql
security definer
set search_path=public
as $$
declare
  v_status text;
begin
  select status into v_status from public.getlink_sales_orders where id=p_order_id for update;
  if not found then raise exception 'sales_order_not_found'; end if;
  if v_status<>'pending' then raise exception 'sales_order_not_pending'; end if;
  delete from public.getlink_sales_orders where id=p_order_id;
  return p_order_id;
end;
$$;

revoke all on function public.getlink_sales_create_order(uuid,uuid,text,jsonb) from public,anon,authenticated;
revoke all on function public.getlink_sales_deliver_order(uuid,uuid) from public,anon,authenticated;
revoke all on function public.getlink_sales_reverse_order(uuid,uuid) from public,anon,authenticated;
revoke all on function public.getlink_sales_delete_pending_order(uuid) from public,anon,authenticated;
grant execute on function public.getlink_sales_create_order(uuid,uuid,text,jsonb) to service_role;
grant execute on function public.getlink_sales_deliver_order(uuid,uuid) to service_role;
grant execute on function public.getlink_sales_reverse_order(uuid,uuid) to service_role;
grant execute on function public.getlink_sales_delete_pending_order(uuid) to service_role;

commit;
