-- Public customer bargain/rating feedback.
-- Direct table access stays closed; Edge Function writes via service role only.

create table if not exists public.getlink_user_product_feedback (
  id bigint generated by default as identity primary key,
  canonical_url text not null,
  client_id text not null,
  bargain_price_vnd bigint,
  rating smallint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint getlink_user_product_feedback_rating_check
    check (rating is null or (rating between 1 and 5)),
  constraint getlink_user_product_feedback_bargain_check
    check (bargain_price_vnd is null or bargain_price_vnd >= 0),
  constraint getlink_user_product_feedback_unique
    unique (canonical_url, client_id)
);

create index if not exists getlink_user_product_feedback_url_updated_idx
  on public.getlink_user_product_feedback(canonical_url, updated_at desc);

alter table public.getlink_user_product_feedback enable row level security;
revoke all on public.getlink_user_product_feedback from anon, authenticated;
