-- Automatic Google Sheets -> Supabase supplier sync.
-- Product identity is product_code; source_row is only the current sheet position.

create table if not exists public.getlink_supplier_sync_runs (
  id bigint generated by default as identity primary key,
  source_key text not null,
  source_name text not null default '',
  status text not null
    check (status in ('running','success','error')),
  fetched_rows integer not null default 0,
  active_rows integer not null default 0,
  inserted_rows integer not null default 0,
  changed_rows integer not null default 0,
  inactive_rows integer not null default 0,
  error text,
  started_at timestamptz not null default now(),
  finished_at timestamptz
);

create index if not exists getlink_supplier_sync_runs_source_time_idx
  on public.getlink_supplier_sync_runs (source_key,started_at desc);

alter table public.getlink_supplier_sync_runs enable row level security;
revoke all on public.getlink_supplier_sync_runs from anon, authenticated;

alter table public.getlink_supplier_products
  drop constraint if exists getlink_supplier_products_source_row_key;

create index if not exists getlink_supplier_products_source_row_idx
  on public.getlink_supplier_products (source_key,source_row);

do $$
declare
  existing_job bigint;
begin
  select jobid into existing_job
  from cron.job
  where jobname='getlink-supplier-sheet-sync'
  limit 1;

  if existing_job is not null then
    perform cron.unschedule(existing_job);
  end if;

  perform cron.schedule(
    'getlink-supplier-sheet-sync',
    '*/5 * * * *',
    $cron$
      select net.http_post(
        url := 'https://gcnoahqsrquxkwkjbuxy.supabase.co/functions/v1/getlink-api/api/supplier-sync/worker',
        headers := jsonb_build_object(
          'content-type','application/json',
          'x-getlink-cron',(select cron_secret from public.getlink_update_settings where id=1)
        ),
        body := '{}'::jsonb
      );
    $cron$
  );
end $$;
